version: "3"
services:
  react-app:
    image: react-app
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    image: api-server
    ports:
      - "5000:5000"
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo:4.0.20-xenial
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
  proxy:
    image: nginx:1.19.4
    restart: unless-stopped
    ports:
      - "8200:80"
    networks:
      - mern-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
